stages:
  - build
  - test
  - report

variables:
  SOLUTION: "UnitTest.sln"
  DOTNET_SDK_VERSION: "8.0"

before_script:
  # output some debug info
  - uname -a
  - echo $SOLUTION
  - echo $DOTNET_SDK_VERSION
  - chmod +x send_discord_notification.sh
  - cd Fractions

build:
  image: "mcr.microsoft.com/dotnet/sdk:$DOTNET_SDK_VERSION"
  stage: build
  script:
    - dotnet format $SOLUTION --verify-no-changes
    - dotnet build $SOLUTION --configuration Release

unit_test:
  image: "mcr.microsoft.com/dotnet/sdk:$DOTNET_SDK_VERSION"
  stage: test
  script:
    - dotnet tool install -g dotnet-reportgenerator-globaltool
    - dotnet add tests/tests.csproj package JunitXml.TestLogger
    - dotnet test $SOLUTION --configuration Release --logger "junit;LogFilePath=dotnet-test-result.xml" --collect:"XPlat Code Coverage"

    # find and print the output file
    - OUTPUT=$(find tests/TestResults | grep xml)
    - echo "${OUTPUT}"
    
    # produce the report
    - /root/.dotnet/tools/reportgenerator -reports:${OUTPUT} -reporttypes:Html -targetdir:html
    - /root/.dotnet/tools/reportgenerator -reports:${OUTPUT} -reporttypes:TextSummary -targetdir:text
  
  artifacts:
    reports:
      junit: Fractions/tests/dotnet-test-result.xml
    paths:
      - Fractions/html
  
run_main:
  image: "mcr.microsoft.com/dotnet/sdk:$DOTNET_SDK_VERSION"
  stage: test
  script:
    - dotnet run $SOLUTION --project console_app --configuration Release


test_sql:
  variables:
    ACCEPT_EULA: Y
    MSSQL_SA_PASSWORD: Plukfisk1234
    
  services:
    - name: mcr.microsoft.com/mssql/server:2022-latest
      alias: mssql
      # entrypoint: ["/usr/local/bin/db-postgres"]
      # command: ["start"]

  #image: "mcr.microsoft.com/dotnet/sdk:$DOTNET_SDK_VERSION"
  #stage: test
  #script:
  #  - dotnet run $SOLUTION --project console_app --configuration Release

  image: "mcr.microsoft.com/mssql-tools"
  stage: test
  script:
    - sqlcmd -S mssql -U sa -P Plukfisk > select @@version > go


report_success:
  stage: report
  when: on_success
  script:
    - echo 'Success'

report_failure:
  stage: report
  when: on_failure
  script:
    - echo 'Failure'
    - cd ..
    - ./send_discord_notification.sh "Build failed"

