stages:
  - build
  - test

variables:
  # Define variables such as the solution file name
  SOLUTION: "Fractions\UnitTest.sln"
  DOTNET_SDK_VERSION: "7.0"

before_script:
  - apt-get update -qy
  - apt-get install -y curl
  - curl -SL --output dotnet-install.sh https://dot.net/v1/dotnet-install.sh
  - chmod +x dotnet-install.sh
  - ./dotnet-install.sh --version $DOTNET_SDK_VERSION --install-dir ~/dotnet
  - export PATH="$PATH:~/dotnet"

build:
  stage: build
  script:
    - dotnet restore $SOLUTION
    - dotnet build $SOLUTION --configuration Release

test:
  stage: test
  script:
    - dotnet test $SOLUTION --configuration Release
