stages:
  - build
  - test

variables:
  SOLUTION: "UnitTest.sln"
  DOTNET_SDK_VERSION: "8.0"

before_script:
  - uname -a
  - cd Fractions

build:
  image: "mcr.microsoft.com/dotnet/sdk:$DOTNET_SDK_VERSION"
  stage: build
  script:
    - dotnet build $SOLUTION --configuration Release

unit_test:
  image: "mcr.microsoft.com/dotnet/sdk:$DOTNET_SDK_VERSION"
  stage: test
  script:
    - dotnet tool install -g dotnet-reportgenerator-globaltool
    - dotnet add package JUnitTestLogger
    - dotnet test $SOLUTION --configuration Release --logger "junit;LogFileName=MyProject.xml"
#    - dotnet test $SOLUTION --configuration Release --collect:"XPlat Code Coverage"
#    - OUTPUT=$(find tests/TestResults | grep xml)
#    - echo "${OUTPUT}"
#    - /root/.dotnet/tools/reportgenerator -reports:${OUTPUT} -reporttypes:Html -targetdir:html

#  artifacts:
#    paths:
#      - Fractions/html
    artifacts:
      reports:
        junit: ./MyProject.xml

run_main:
  image: "mcr.microsoft.com/dotnet/sdk:$DOTNET_SDK_VERSION"
  stage: test
  script:
    - dotnet run $SOLUTION --project console_app --configuration Release







